<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2019 Giovanni di Dio Bruno https://gbr1.github.io

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->
<robot name="power_switch" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="power_switch" params="offset_x offset_y offset_z">

        <xacro:property name="ps_size_x" value="0.025" />
        <xacro:property name="ps_size_y" value="0.019" />
        <xacro:property name="ps_size_z" value="0.022" />
        <xacro:property name="ps_mass" value="0.010" />
        
        <link name="power_switch_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${ps_mass}" />
                <inertia ixx="${ps_mass*(ps_size_y*ps_size_y+ps_size_z*ps_size_z)}" ixy="0" ixz="0"
                         iyy="${ps_mass*(ps_size_x*ps_size_x+ps_size_z*ps_size_z)}" iyz="0"
                         izz="${ps_mass*(ps_size_x*ps_size_x+ps_size_y*ps_size_y)}" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 ${-M_PI_2} ${M_PI_2}" />
                <geometry>
                    <mesh filename="${path_meshes}/power_switch.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="erwhi_black" />
            </visual>
            <collision>
                <origin xyz="${ps_size_x/4} 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${ps_size_x} ${ps_size_y} ${ps_size_z}" />
                </geometry>
            </collision>
        </link>
        <joint name="power_switch_joint" type="fixed">
            <parent link="base_link" />
            <child link="power_switch_link" />
            <origin rpy="0 0 0" xyz="${offset_x} ${offset_y} ${offset_z}"/>
        </joint>
        <gazebo reference="power_switch_link">
            <turnGravityOff>false</turnGravityOff>
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro> 
</robot>